"""add ai_generated_quotes table

Revision ID: 1427a3daec95
Revises: 417be222b16e
Create Date: 2026-04-21 11:47:45.299733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1427a3daec95'
down_revision: Union[str, Sequence[str], None] = '417be222b16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generated_quotes', sa.Column('extracted_items', sa.JSON(), nullable=True))
    op.drop_column('ai_generated_quotes', 'extracted_items_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generated_quotes', sa.Column('extracted_items_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ai_generated_quotes', 'extracted_items')
    # ### end Alembic commands ###
