"""add request_hash to invoices and quotes

Revision ID: 37dd9cb43726
Revises: 445c7bb22e8a
Create Date: 2026-06-12 01:52:11.042349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dd9cb43726'
down_revision: Union[str, Sequence[str], None] = '445c7bb22e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('request_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_request_hash'), 'invoices', ['request_hash'], unique=True)
    op.add_column('quotes', sa.Column('request_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_quotes_request_hash'), 'quotes', ['request_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_request_hash'), table_name='quotes')
    op.drop_column('quotes', 'request_hash')
    op.drop_index(op.f('ix_invoices_request_hash'), table_name='invoices')
    op.drop_column('invoices', 'request_hash')
    # ### end Alembic commands ###
