"""update quotes and invoices schema

Revision ID: 417be222b16e
Revises: 6438344d3a19
Create Date: 2026-04-21 11:33:08.302840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417be222b16e'
down_revision: Union[str, Sequence[str], None] = '6438344d3a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'is_finalized',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'is_finalized',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
