"""add unique constraints for quote

Revision ID: 445c7bb22e8a
Revises: 1427a3daec95
Create Date: 2026-06-12 00:05:31.087183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445c7bb22e8a'
down_revision: Union[str, Sequence[str], None] = '1427a3daec95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quotes', ['client_quote_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    # ### end Alembic commands ###
